insert into projects (
  id,
  path,
  name,
  enabled,
  repo_kind,
  product,
  branch_policy,
  push_policy,
  milestone_tag_policy
) values
  ('auth-ui', '../auth-ui', 'auth-ui', true, 'nested_git', 'auth', 'main_verified_slice', 'push_after_verified_slice', 'phase_closeout'),
  ('auth-server', '../auth-server', 'auth-server', true, 'nested_git', 'auth', 'main_verified_slice', 'push_after_verified_slice', 'phase_closeout'),
  ('ai-engineering-system', '../ai-engineering-system', 'ai-engineering-system', true, 'nested_git', 'ai-engineering', 'main_verified_slice', 'push_after_verified_slice', 'release_only'),
  ('cms-admin', '../cms-admin', 'cms-admin', true, 'root_folder', 'cms', 'main_verified_slice', 'push_after_verified_slice', 'phase_closeout'),
  ('cms-api', '../cms-api', 'cms-api', true, 'root_folder', 'cms', 'main_verified_slice', 'push_after_verified_slice', 'phase_closeout'),
  ('community-api', '../community-api', 'community-api', true, 'nested_git', 'community', 'main_verified_slice', 'push_after_verified_slice', 'phase_closeout'),
  ('community-web', '../community-web', 'community-web', true, 'nested_git', 'community', 'main_verified_slice', 'push_after_verified_slice', 'phase_closeout'),
  ('form-admin', '../form-admin', 'form-admin', true, 'root_folder', 'forms', 'main_verified_slice', 'push_after_verified_slice', 'phase_closeout'),
  ('form-api', '../form-api', 'form-api', true, 'root_folder', 'forms', 'main_verified_slice', 'push_after_verified_slice', 'phase_closeout'),
  ('form-web', '../form-web', 'form-web', true, 'root_folder', 'forms', 'main_verified_slice', 'push_after_verified_slice', 'phase_closeout'),
  ('interview-api', '../interview-api', 'interview-api', true, 'nested_git', 'interview', 'main_verified_slice', 'manual_only', 'phase_closeout'),
  ('interview-web', '../interview-web', 'interview-web', true, 'nested_git', 'interview', 'main_verified_slice', 'manual_only', 'phase_closeout'),
  ('knowledge-api', '../knowledge-api', 'knowledge-api', true, 'nested_git', 'knowledge', 'main_verified_slice', 'push_after_verified_slice', 'phase_closeout'),
  ('knowledge-web', '../knowledge-web', 'knowledge-web', true, 'nested_git', 'knowledge', 'main_verified_slice', 'push_after_verified_slice', 'phase_closeout'),
  ('language-api', '../language-api', 'language-api', true, 'nested_git', 'language', 'main_verified_slice', 'push_after_verified_slice', 'phase_closeout'),
  ('language-web', '../language-web', 'language-web', true, 'nested_git', 'language', 'main_verified_slice', 'push_after_verified_slice', 'phase_closeout'),
  ('office-empire-simulator', '../office-empire-simulator', 'office-empire-simulator', true, 'nested_git', 'office-game', 'main_verified_slice', 'manual_only', 'phase_closeout'),
  ('orchestra', '../orchestra', 'orchestra', true, 'nested_git', 'orchestra', 'main_verified_slice', 'push_after_verified_slice', 'release_only'),
  ('portal-api', '../portal-api', 'portal-api', true, 'nested_git', 'portal', 'main_verified_slice', 'push_after_verified_slice', 'phase_closeout'),
  ('portal-web', '../portal-web', 'portal-web', true, 'nested_git', 'portal', 'main_verified_slice', 'push_after_verified_slice', 'phase_closeout'),
  ('realtime-service', '../realtime-service', 'realtime-service', true, 'nested_git', 'community', 'main_verified_slice', 'push_after_verified_slice', 'phase_closeout'),
  ('trading-api', '../trading-api', 'trading-api', true, 'root_folder', 'trading', 'main_verified_slice', 'push_after_verified_slice', 'phase_closeout'),
  ('trading-web', '../trading-web', 'trading-web', true, 'root_folder', 'trading', 'main_verified_slice', 'push_after_verified_slice', 'phase_closeout')
on conflict (id) do update set
  path = excluded.path,
  name = excluded.name,
  enabled = excluded.enabled,
  repo_kind = excluded.repo_kind,
  product = excluded.product,
  branch_policy = excluded.branch_policy,
  push_policy = excluded.push_policy,
  milestone_tag_policy = excluded.milestone_tag_policy,
  updated_at = now();

